/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package br.ufba.smelldetector;

import static br.ufba.limiares.GerarLimiares.getMetricasProjetos;
import br.ufba.limiares.GerenciadorLimiares;
import br.ufba.smelldetector.model.DadosMetodoSmell;
import br.ufba.smelldetector.model.LimiarTecnica;
import br.ufba.smelldetector.negocio.CarregaSalvaArquivo;
import br.ufba.smelldetector.negocio.FiltrarMetodosSmell;
import com.github.mauricioaniche.ck.CKNumber;
import java.awt.Cursor;
import java.io.File;
import java.io.FileNotFoundException;
import java.util.ArrayList;
import java.util.HashMap;
import java.util.Scanner;
import javax.swing.JOptionPane;
import java.util.List;

/**
 *
 * @author Marcos
 */
public class SmellDetectorView extends javax.swing.JFrame {

    /**
     * Creates new form SmellDetectorView
     */
    public SmellDetectorView() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jToggleButton1 = new javax.swing.JToggleButton();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("ContextSmell Desktop");

        jLabel1.setText("Step 1) Add Reference Projects to file Reference.txt");

        jLabel2.setText("Step 2) Generate Thresholds and Design Roles from Reference Projects");

        jToggleButton1.setSelected(true);
        jToggleButton1.setText("Generate Contextual Thresholds");
        jToggleButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jToggleButton1ActionPerformed(evt);
            }
        });

        jLabel3.setText("Step 5) Check out the Design Role Spreedsheet DR.csv. Are Design Roles correct?");

        jLabel4.setText("Step 4) Execute Analysis");

        jButton1.setText("Start Analysys");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jLabel6.setText("Step 3) Add Projects for Analysis to Analysis.txt");

        jLabel7.setText("Step 6) Check out the Smells Spreedsheet SMELLS.csv. Do you agree to refactor them?");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addComponent(jLabel2)
                    .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jToggleButton1)
                    .addComponent(jLabel6)
                    .addComponent(jLabel7)
                    .addComponent(jLabel4)
                    .addComponent(jLabel3))
                .addGap(0, 20, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jToggleButton1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel6)
                .addGap(10, 10, 10)
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jButton1)
                .addGap(18, 18, 18)
                .addComponent(jLabel3)
                .addGap(18, 18, 18)
                .addComponent(jLabel7)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jToggleButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jToggleButton1ActionPerformed
	 try {
             this.setCursor(Cursor.getPredefinedCursor(Cursor.WAIT_CURSOR));
             System.out.println("Iniciando a coleta de métricas do projeto referencia...");
             ArrayList<String> projetosReferencia = lerProjetos("Reference.txt");
             ArrayList<CKNumber> metricasProjetosReferencia = getMetricasProjetos(projetosReferencia);
             GerenciadorLimiares gLimiares = new GerenciadorLimiares();
             gLimiares.gerarDesignRoles(metricasProjetosReferencia, "DR.CSV");
             gLimiares.gerarLimiarDoseaDesignRolePercentil(metricasProjetosReferencia, "thresholds\\D.csv");
             gLimiares.gerarLimiarDoseaPercentil(metricasProjetosReferencia, "thresholds\\R.csv");
             JOptionPane.showMessageDialog(null, "Thresholds generated with success!");
         } catch(Exception e) {
             JOptionPane.showMessageDialog(null, "Problems to generate thresholds!" + e.getMessage());
         } finally {
            this.setCursor(Cursor.getDefaultCursor());
        }
    }//GEN-LAST:event_jToggleButton1ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
         try {
             this.setCursor(Cursor.getPredefinedCursor(Cursor.WAIT_CURSOR));
             System.out.println("Iniciando a coleta de métricas do projeto a ser analisado...");
             ArrayList<String> projetosAnalisar = lerProjetos("Analysis.txt");
             ArrayList<CKNumber> metricasProjetosAnalisar = getMetricasProjetos(projetosAnalisar);
	     List<LimiarTecnica> listaTecnicas = CarregaSalvaArquivo.carregarLimiares(System.getProperty("user.dir") + "\\thresholds\\");
             
             HashMap<String, DadosMetodoSmell> metodosSmell = null;
	     metodosSmell = FiltrarMetodosSmell.filtrar(metricasProjetosAnalisar, listaTecnicas, metodosSmell);
             FiltrarMetodosSmell.gravarMetodosSmell(metodosSmell, "SMELLS.csv");
             JOptionPane.showMessageDialog(null, "Smells generated with success!");
         } catch(Exception e) {
             JOptionPane.showMessageDialog(null, "Problems to generate smells!" + e.getMessage());
         } finally {
            this.setCursor(Cursor.getDefaultCursor());
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    private static ArrayList<String> lerProjetos(String nomeArquivo) {
        ArrayList<String> projetos = new ArrayList<>();
        String arquivo = System.getProperty("user.dir") + "\\" + nomeArquivo;
        File file = new File(arquivo);
        try {
            if (file.exists()) {
                Scanner scanner = new Scanner(file);
                while (scanner.hasNext()) {
                    projetos.add(scanner.next());
                }
                scanner.close();
            }
        } catch (FileNotFoundException e) {
            System.out.println("Arquivo não encontrados: " + arquivo);
        }
        return projetos;
    }
    
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(SmellDetectorView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(SmellDetectorView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(SmellDetectorView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(SmellDetectorView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new SmellDetectorView().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JToggleButton jToggleButton1;
    // End of variables declaration//GEN-END:variables
}
